name: xboard_onefile
description: XBoard login & subscribe app
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
